packages:
  - .
  - playground
catalog:
  '@nuxt/kit': ^3.17.7
  '@nuxt/schema': ^3.17.7
  '@unocss/nuxt': ^66.3.3
  '@unocss/reset': ^66.3.3
  '@vitest/coverage-v8': ^3.2.4
  medium-zoom: ^1.1.0
  nuxt: ^3.17.7
  unocss: ^66.3.3
  vitest: ^3.2.4
overrides:
  esbuild: ^0.25.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
