packages:
  - playground
catalog:
  '@nuxt/kit': ^4.1.3
  '@nuxt/schema': ^4.1.3
  '@unocss/nuxt': ^66.5.3
  '@unocss/reset': ^66.5.3
  medium-zoom: ^1.1.0
  nuxt: ^4.1.3
  unocss: ^66.5.3
  vitest: ^3.2.4
overrides:
  esbuild: ^0.25.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
