packages:
  - playground
catalog:
  '@nuxt/kit': ^4.2.2
  '@nuxt/schema': ^4.2.2
  '@unocss/nuxt': ^66.5.12
  '@unocss/reset': ^66.5.12
  medium-zoom: ^1.1.0
  nuxt: ^4.2.2
  unocss: ^66.5.12
  vitest: ^4.0.16
overrides:
  esbuild: ^0.27.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
