packages:
  - .
  - playground
catalog:
  '@nuxt/kit': ^3.16.2
  '@nuxt/schema': ^3.16.2
  '@unocss/nuxt': ^66.1.0-beta.12
  '@unocss/reset': ^66.1.0-beta.12
  '@vitest/coverage-v8': ^3.1.1
  medium-zoom: ^1.1.0
  nuxt: ^3.16.2
  unocss: ^66.1.0-beta.12
  vitest: ^3.1.1
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
