catalog:
  '@nuxt/kit': ^3.15.4
  '@nuxt/schema': ^3.15.4
  '@unocss/nuxt': ^66.0.0
  '@unocss/reset': ^66.0.0
  '@vitest/coverage-v8': ^3.0.6
  medium-zoom: ^1.1.0
  nuxt: ^3.15.4
  unocss: ^66.0.0
  vitest: ^3.0.6
packages:
  - .
  - playground
