catalog:
  '@nuxt/kit': ^3.15.4
  '@nuxt/schema': ^3.15.4
  '@unocss/nuxt': ^65.4.3
  '@unocss/reset': ^65.4.3
  '@vitest/coverage-v8': ^3.0.5
  medium-zoom: ^1.1.0
  nuxt: ^3.15.4
  unocss: ^65.4.3
  vitest: ^3.0.5
packages:
  - .
  - playground
