packages:
  - playground
catalog:
  '@nuxt/kit': ^4.2.1
  '@nuxt/schema': ^4.2.1
  '@unocss/nuxt': ^66.5.9
  '@unocss/reset': ^66.5.9
  medium-zoom: ^1.1.0
  nuxt: ^4.2.1
  unocss: ^66.5.9
  vitest: ^4.0.14
overrides:
  esbuild: ^0.25.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
