packages:
  - .
  - playground
catalog:
  '@nuxt/kit': ^3.17.1
  '@nuxt/schema': ^3.17.1
  '@unocss/nuxt': ^66.1.0
  '@unocss/reset': ^66.1.0
  '@vitest/coverage-v8': ^3.1.2
  medium-zoom: ^1.1.0
  nuxt: ^3.17.1
  unocss: ^66.1.0
  vitest: ^3.1.2
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
