catalog:
  '@nuxt/kit': ^3.15.2
  '@nuxt/schema': ^3.15.2
  '@unocss/nuxt': ^65.4.2
  '@unocss/reset': ^65.4.2
  '@vitest/coverage-v8': ^3.0.0-beta.4
  medium-zoom: ^1.1.0
  nuxt: ^3.15.2
  unocss: ^65.4.2
  vitest: ^3.0.0-beta.4
packages:
  - .
  - playground
