packages:
  - playground
catalog:
  '@nuxt/kit': ^4.2.0
  '@nuxt/schema': ^4.2.0
  '@unocss/nuxt': ^66.5.4
  '@unocss/reset': ^66.5.4
  medium-zoom: ^1.1.0
  nuxt: ^4.2.0
  unocss: ^66.5.4
  vitest: ^4.0.6
overrides:
  esbuild: ^0.25.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
