packages:
  - playground
catalog:
  '@nuxt/kit': ^4.3.0
  '@nuxt/schema': ^4.3.0
  '@unocss/nuxt': ^66.6.0
  '@unocss/reset': ^66.6.0
  medium-zoom: ^1.1.0
  nuxt: ^4.3.0
  unocss: ^66.6.0
  vitest: ^4.0.18
overrides:
  esbuild: ^0.27.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
