packages:
  - .
  - playground
catalog:
  '@nuxt/kit': ^3.17.3
  '@nuxt/schema': ^3.17.3
  '@unocss/nuxt': ^66.1.2
  '@unocss/reset': ^66.1.2
  '@vitest/coverage-v8': ^3.1.3
  medium-zoom: ^1.1.0
  nuxt: ^3.17.3
  unocss: ^66.1.2
  vitest: ^3.1.3
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
